name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Cyb3r-Jak3/html5validator-action
        with:
          root: src/
          blacklist: invalid
