name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -d --rm -p 8888:8888 ghcr.io/validator/validator:latest
      - run: vnu-runtime-image/bin/vnu src/*.html
